version: '3.8'

services:
  hairstyle-ai:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
      - ./static:/app/static
    environment:
      - FLASK_ENV=production
      - DATABASE_PATH=/app/data/hairstyle_booking.db
    restart: unless-stopped
